# Generated by Django 4.1.7 on 2023-03-28 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_product_created_at_product_discount_product_price'),
        ('shopapp', '0007_alter_product_options'),
    ]

    operations = [
    ]
