# Generated by Django 4.1.4 on 2022-12-16 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='image',
        ),
        migrations.CreateModel(
            name='GoodImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/goods/')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='app_market.good', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'изображение',
                'verbose_name_plural': 'изображения',
                'db_table': 'good_images',
                'ordering': ['id'],
            },
        ),
    ]
