# Generated by Django 4.1.4 on 2022-12-22 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('published_at', models.DateTimeField(auto_now=True, verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовать новость')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'новость',
                'verbose_name_plural': 'новости',
                'db_table': 'news',
                'ordering': ['published_at'],
            },
        ),
    ]
