# Generated by Django 4.1.4 on 2022-12-22 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0002_news_content_alter_news_published_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-is_published', '-published_at'], 'verbose_name': 'новость', 'verbose_name_plural': 'новости'},
        ),
    ]
