# Generated by Django 4.1.4 on 2022-12-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0002_remove_good_image_goodimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/goods/'),
        ),
    ]
