# Generated by Django 3.2.18 on 2023-04-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='имя автора')),
                ('family', models.CharField(max_length=200, verbose_name='фамилия автора')),
                ('birth_year', models.FloatField(verbose_name='год рождения')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название книги')),
                ('isbn', models.FloatField(verbose_name='международный стандартный книжный номер')),
                ('year', models.FloatField(verbose_name='год выпуска')),
                ('pages', models.IntegerField(verbose_name='количество страниц')),
            ],
        ),
    ]
