# Generated by Django 3.2.18 on 2023-04-23 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_libs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app_libs.author', verbose_name='автор книги'),
        ),
        migrations.AlterField(
            model_name='author',
            name='birth_year',
            field=models.IntegerField(verbose_name='год рождения'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.TextField(verbose_name='международный стандартный книжный номер'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.IntegerField(verbose_name='год выпуска'),
        ),
    ]
