# Generated by Django 4.1.4 on 2022-12-22 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='RoomsAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1, verbose_name='Количество комнат')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_rooms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_amount', to='app_houses.roomsamount', verbose_name='Количество комнат')),
                ('house_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_type', to='app_houses.housetype', verbose_name='Тип помещения')),
            ],
        ),
    ]
