# Generated by Django 4.1.4 on 2022-12-22 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_houses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': ['id'], 'verbose_name': 'жилое помещение', 'verbose_name_plural': 'жилые помещения'},
        ),
        migrations.AlterModelOptions(
            name='housetype',
            options={'ordering': ['id'], 'verbose_name': 'тип помещения', 'verbose_name_plural': 'типы помещений'},
        ),
        migrations.AlterModelOptions(
            name='roomsamount',
            options={'ordering': ['id'], 'verbose_name': 'комната', 'verbose_name_plural': 'комнаты'},
        ),
        migrations.AlterModelTable(
            name='house',
            table='houses',
        ),
        migrations.AlterModelTable(
            name='housetype',
            table='house_types',
        ),
        migrations.AlterModelTable(
            name='roomsamount',
            table='house_rooms',
        ),
    ]
