# Generated by Django 4.1.4 on 2022-12-22 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_houses', '0002_alter_house_options_alter_housetype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='housetype',
            options={'ordering': ['title'], 'verbose_name': 'тип помещения', 'verbose_name_plural': 'типы помещений'},
        ),
    ]
