# Generated by Django 4.1.4 on 2022-12-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_houses', '0003_alter_housetype_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='housetype',
            options={'ordering': ['id'], 'verbose_name': 'тип помещения', 'verbose_name_plural': 'типы помещений'},
        ),
        migrations.AddField(
            model_name='housetype',
            name='prestige_grade',
            field=models.IntegerField(default=1, verbose_name='Уровень престижности'),
        ),
    ]
