# Generated by Django 4.1.4 on 2022-12-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_houses', '0005_alter_housetype_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='address',
            field=models.CharField(blank=True, max_length=500, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='house',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
    ]
