# Generated by Django 4.1.4 on 2022-12-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_houses', '0006_house_address_house_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена (в тыс. у.е.)'),
        ),
    ]
