# Generated by Django 4.1.3 on 2022-12-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAvatars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_file', models.FileField(upload_to='images/user_avatars/')),
            ],
        ),
    ]
