# Generated by Django 4.1.3 on 2022-12-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0005_useravatars'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAvatars',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_file',
            field=models.FileField(default=1, upload_to='images/user_avatars/'),
            preserve_default=False,
        ),
    ]
