# Generated by Django 4.1.3 on 2022-12-08 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_profile_phone_alter_profile_birthday_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['id'], 'verbose_name': 'профиль', 'verbose_name_plural': 'профили'},
        ),
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
    ]
