# Generated by Django 4.1.4 on 2022-12-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0008_alter_profile_avatar_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Титул')),
                ('expenses_lt', models.IntegerField(verbose_name='Порог перехода')),
            ],
            options={
                'verbose_name': 'статус',
                'verbose_name_plural': 'статусы',
                'db_table': 'statuses',
                'ordering': ['expenses_lt'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='balance',
            field=models.FloatField(default=0, verbose_name='Баланс'),
        ),
    ]
