# Generated by Django 4.1.4 on 2022-12-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0009_userstatus_profile_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_status',
            field=models.IntegerField(default=1, verbose_name='ID старого статуса'),
        ),
    ]
