# Generated by Django 4.1.4 on 2022-12-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('expire_at', models.DateTimeField(blank=True, null=True, verbose_name='Срок окончания')),
                ('is_archive', models.BooleanField(default=False, verbose_name='Архив')),
            ],
            options={
                'verbose_name': ('предложение',),
                'verbose_name_plural': ('предложения',),
                'db_table': 'offers',
                'ordering': ['-expire_at'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('expire_at', models.DateTimeField(blank=True, null=True, verbose_name='Срок окончания')),
                ('is_archive', models.BooleanField(default=False, verbose_name='Архив')),
            ],
            options={
                'verbose_name': ('акция',),
                'verbose_name_plural': ('акции',),
                'db_table': 'promotions',
                'ordering': ['-expire_at'],
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название магазина')),
                ('offers', models.ManyToManyField(related_name='offers', to='app_shop.offer', verbose_name='Предложения')),
                ('promotions', models.ManyToManyField(related_name='promotions', to='app_shop.promotion', verbose_name='Акции')),
            ],
            options={
                'verbose_name': ('магазин',),
                'verbose_name_plural': ('магазины',),
                'db_table': 'shops',
                'ordering': ['title'],
            },
        ),
    ]
