# Generated by Django 4.1.4 on 2022-12-23 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['-expire_at'], 'verbose_name': 'предложение', 'verbose_name_plural': 'предложения'},
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ['-expire_at'], 'verbose_name': 'акция', 'verbose_name_plural': 'акции'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['title'], 'verbose_name': 'магазин', 'verbose_name_plural': 'магазины'},
        ),
    ]
