# Generated by Django 4.1.4 on 2022-12-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_money',
            field=models.FloatField(default=0, verbose_name='Сумма покупки'),
        ),
    ]
